export const WEAPON_GROUPS = {
  brawl: "DGNS.WEAPON.brawl",
  armedMelee: "DGNS.WEAPON.armedMelee",
  thrown: "DGNS.WEAPON.thrown",
  projectiles: "DGNS.WEAPON.projectiles",
  handguns: "DGNS.WEAPON.handguns",
  rifles: "DGNS.WEAPON.rifles",
  heavy: "DGNS.WEAPON.heavy",
  explosives: "DGNS.WEAPON.explosives",
  sonic: "DGNS.WEAPON.sonic",
  custom: "DGNS.WEAPON.custom",
};

export const WEAPON_GROUPS_SKILLS = {
  brawl: "brawl",
  armedMelee: "melee",
  thrown: "projectiles",
  projectiles: "projectiles",
  handguns: "projectiles",
  rifles: "projectiles",
  heavy: "projectiles",
  explosives: "projectiles",
  sonic: "engineering",
  custom: "",
};

export const CALIBERS = {
  "50gl": "DGNS.CALIBER.50gl",
  357: "DGNS.CALIBER.357",
  44: "DGNS.CALIBER.44",
  "410sh": "DGNS.CALIBER.410sh",
  "410sl": "DGNS.CALIBER.410sl",
  556: "DGNS.CALIBER.556",
  jacket: "DGNS.CALIBER.jacket",
  hollowPoint: "DGNS.CALIBER.hollowPoint",
  flechette: "DGNS.CALIBER.flechette",
  "46x30": "DGNS.CALIBER.46x30",
  "9mm": "DGNS.CALIBER.9mm",
  "5x30": "DGNS.CALIBER.5x30",
  762: "DGNS.CALIBER.762",
  14: "DGNS.CALIBER.14",
  buckshot: "DGNS.CALIBER.buckshot",
  rifleBarrel: "DGNS.CALIBER.rifleBarrel",
  cartridge: "DGNS.CALIBER.cartridge",
  grenade: "DGNS.CALIBER.grenade",
  missile: "DGNS.CALIBER.missile",
  fragger: "DGNS.CALIBER.fragger",
  blackpowder: "DGNS.CALIBER.blackpowder",
  leadbullet: "DGNS.CALIBER.leadbullet",
  Ecube: "DGNS.CALIBER.Ecube",
  arrow: "DGNS.CALIBER.arrow",
  bolt: "DGNS.CALIBER.bolt",
  petro: "DGNS.CALIBER.petro",
  harpoon: "DGNS.CALIBER.harpoon",
  nail: "DGNS.CALIBER.nail",
  coal: "DGNS.CALIBER.coal",
  boltcoal: "DGNS.CALIBER.boltcoal",
  special: "DGNS.CALIBER.special",
  custom: "DGNS.CALIBER.custom",
};

export const EQUIPMENT_GROUPS = {};
